mysite/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
	path('createaccount/', views.signup_view, name="signup"),
	path('login/', views.login_view, name="login"),
	path('logout/', views.logout_view, name="logout"),
	path('userlogin', views.user_login, name="userlogin"),

]

mysite/envapps/urls.py
from django.urls import path
from . import views

app_name = 'envapps'
urlpatterns = [
    path('', views.storm_apps, name="storm_apps"),
    path('ossf_app/', views.ossf_app, name="ossf_app"),
	#path('/home/createaccount/', views.signup_view, name = "signup")
	#path('/accounts/login', views.login_view, name = "login")
	#path('/accounts/logout', views.logout_view, name = "logout")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', views.home),
	path('envapps/', include('envapps.urls')),
	path('accounts/', include('accounts.urls')),

	]

urlpatterns += staticfiles_urlpatterns()

mysite/templates/error.html
{% extends "layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>
    {{ message }}
{% endblock %}

mysite/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Web Page!</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>
            .row > div {
                padding: 20px;
                background-color: white;
                border: 2px solid black;
            }

            .row > table {
                padding-left: 145px;
            }
            .center-block() {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            table {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <img src="http://static1.squarespace.com/static/57f09087ebbd1aa018c6197c/57f0931ed482e918dc2fc675/5ad15d9f575d1f10b3b0ae02/1523723873168/welcome+picture.jpg?format=1000w" alt="Welcome" width=100% height=100%>
                </div>
  <form class="px-4 py-3">
    <form class="login-link" action = "{% 'accounts/login.html' %}" method = "post">
        <button class="btn btn-primary"> Log In </button>
    </form>
  </form>



    </body>
</html>

mysite/templates/layout.html
<!DOCTYPE html>
  <html>
      <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
          <style>
                .navbar,.navbar-brand{
                                        background-color: #7FFFD4;
                                      }

                                  li {
                                        text-decoration-color: black;
                                        font-weight: bolder;

                                      }

                                   h1,p{
                                        text-align: center;
                                      }
            </style>

    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">Welcome!</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'accounts:userlogin' %}" method='post'>Home</a></li>
                    <li><a href="{% url 'envapps:storm_apps' %}" method='post'>Stormwater Permittng</a></li>
                    <li><a href="{% url 'envapps:ossf_app' %}" method='post'>Septic Permitting</a></li>
                    <li><a href="#">Page 3</a></li>
                    <li>
                      <form class="logout-link" action = "{% url 'accounts:logout' %}" method = "post">
                        {% csrf_token %}
                        <div class="form-group">
                          <button class="btn btn-primary"> Log Out </button>
                        </div>
                         <!--<button type = "submit">Logout</button>-->
                        </form>
                </ul>
            </div>
        </nav>
      <div class="jumbotron">
            <div class="container-fluid">
                <div class="col-12">
                  <h1>{% block jumbotext %}{% endblock %}</h1>
                </div>
            </div>
      </div>
      <div class="container">
            {% block body %}
            {% endblock %}
      </div>
    </body>
    </html>

mysite/templates/login.html
{% extends "layout.html" %}

{% block content %}
	<h1>Log In</h1>

	<form class = "" action="{% url 'accounts:login'%}" method = "POST">

		{% csrf_token%}

	 {{ form }}

	 <input type = "submit" value = "Login">

	</form>

{% endblock%}

mysite/templates/signup.html
{% extends layout.html %}

{% block content %}
	<h1> Signup </h1>

	<form class = "" action="/accounts/signup/" method = "POST">

		{% csrf_token%}

	 {{ form }}

	 <input type = "submit" value = "signup">

	</form>

{% endblock%}

mysite/templates/stormpermitapp.html
{% extends "layout.html" %}

{% block title %} Storm Water Permit Application {% endblock %}

{% block jumbotext %} <h1>Stormwater Site Development Permit Applicaton</h1> <p>All Fields Are Required For Applicaiton Submittal, Incomplete Applications Will Not Be Processed.</p>
{% endblock %}

{% block body %}    	

    <form action="{{ url_for('storm_app_submit') }}" method="POST">
    	<div class="form-group">
    		<label for="projname"> Project Name: </label>
    		<input type="text" class="form-control" name="projname"><br>
    					
    		<label for="app_date"> Date of Application: </label>
    		<input type="Date" class="form-control" name="app_date"><br>
    				
    		<label for="projectlocation"> Project Location: </label>
    		<input type="text" class="form-control" name="projectlocation"><br>

    		<label for="owner_fname"> Owner/Developer First Name: </label>
    		<input type="text" class="form-control" name="owner_fname"><br>

            <label for="owner_lname"> Owner/Developer Last Name: </label>
            <input type="text" class="form-control" name="owner_lname"><br>

    		<label for="owner_address"> Owner/Developer Address: </label>
    		<input type="text" class="form-control" name="owner_address"><br>

    		<label for="phonenumber"> Phone: </label>
    		<input type="text" class="form-control" name="phonenumber"><br>

    		<label for="tceq_noi"> TCEQ NOI Number: </label>
    		<input type="text" class="form-control" name="tceq_noi">    			
    	 
    		<label for="contact_fname"> Site Manager First Name: </label>
    		<input type="text" class="form-control" name="site_contact_fname"><br>

            <label for="contact_lname"> Site Manager Last Name: </label>
            <input type="text" class="form-control" name="site_contact_lname"><br>

    		<label for="contactphone"> Site Manager Phone: </label>
    		<input type="text" class="form-control" name="site_contactphone"><br>

    		<label for="contactemail"> Site Manager Email: </label>
    		<input type="email" class="form-control" name="site_contactemail"><br>

            <label for="inspect_fname"> Inspector First Name: </label>
            <input type="text" class="form-control" name="inspect_fname"><br>

            <label for="inspect_lname"> Inspector Last Name: </label>
            <input type="text" class="form-control" name="inspect_lname"><br>

            <label for="inspect_phone"> Inspector Phone: </label>
            <input type="text" class="form-control" name="inspect_phone"><br>
    						
    		<label for="inspectcontact"> Inspector Email: </label>
			<input type="email" class="form-control" name="inspect_email"><br>
    						
    		<label for="startdate"> Work Start Date: </label>
    		<input type="Date" class="form-control" name="startdate"><br>    				
    		
    		<label for="plat"> Plat number: </label>
    		<input type="text" class="form-control" name="plat_id"><br>

    		<label for="lot"> Lot: </label>
    		<input type="text" class="form-control" name="lot_id"><br>
    					
    		<label for="block"> Block: </label>
    		<input type="text" class="form-control" name="block_id">
        </div>
    	<div class="container">
			<label class="custom-file">Upload Files<input type="file" id="file" class="custom-file-input">
				<span class="custom-file-control"></span>
			</label>
		</div>
   		<div class="form-group">
             <button class="btn btn-primary"> Submit Application </button>
        </div>
    </form>
{% endblock %}

mysite/templates/success.html
{% extends "layout.html" %}

{% block title %}
    Success!
{% endblock %}

{% block body %}
    <h1>Success!</h1>

    You have successfully created your account.
{% endblock %}

mysite/templates/untitled.html
{% extends "layout.html" %}

{% block title %}
    Flights
{% endblock %}

{% block body %}
    <h1>Book a Flight</h1>

    <form action="{{ url_for('book') }}" method="post">

        <div class="form-group">
            <select class="form-control" name="flight_id">
                {% for flight in flights %}
                    <option value="{{ flight.id }}">{{ flight.origin }} to {{ flight.destination }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <input class="form-control" name="name" placeholder="Passenger Name">
        </div>

        <div class="form-group">
            <button class="btn btn-primary">Book Flight</button>
        </div>

    </form>
{% endblock %}